# Generated by Django 4.2 on 2023-04-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
